name: find_config
description: Find configuration files recursively in parent directories
version: 1.2.0
homepage: https://www.github.com/devkabiir/find_config
author: Dinesh Ahuja <dev@kabiir.me>
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  file: ^5.0.0
  path: ^1.6.0

dev_dependencies:
  test: ^1.0.0
  pre_commit:
    git: https://www.github.com/devkabiir/pre_commit
